module.exports = Object.freeze({
    SUCCESS : 200,
    BAD_REQUEST: 400,
    INTERNAL_SERVER_ERROR: 500,
    INVALID_TOKEN: 401,
    EXPIRED_TOKEN: 401,
    STATUS_RUNNING: 'RUNNING',
    STATUS_ERROR: 'ERROR',
    STATUS_COMPLETE:'COMPLETED',
    OPT_KEY_PV_FEE: "pv_fee"
});